export const CATEGORY_OPTIONS = [
  { label: "Cócteles", value: "alcohol cocktail" },
  { label: "Galletas", value: "biscuits and cookies" },
  { label: "Pan", value: "bread" },
  { label: "Cereales", value: "cereals" },
  { label: "Salsas", value: "condiments and sauces" },
  { label: "Postres", value: "desserts" },
  { label: "Bebidas", value: "drinks" },
  { label: "Huevo", value: "egg" },
  { label: "Helados y cremas", value: "ice cream and custard" },
  { label: "Plato principal", value: "main course" },
  { label: "Tortitas", value: "pancake" },
  { label: "Pasta", value: "pasta" },
  { label: "Bollería", value: "pastry" },
  { label: "Tartas", value: "pies and tarts" },
  { label: "Pizza", value: "pizza" },
  { label: "Preparaciones", value: "preps" },
  { label: "Conservas", value: "preserve" },
  { label: "Ensaladas", value: "salad" },
  { label: "Sándwiches", value: "sandwiches" },
  { label: "Marisco", value: "seafood" },
  { label: "Guarnición", value: "side dish" },
  { label: "Sopas", value: "soup" },
  { label: "Celebraciones", value: "special occasions" },
  { label: "Entrantes", value: "starter" },
  { label: "Dulces", value: "sweets" }
];

export const MEAL_TYPE_OPTIONS = [
  { label: "Desayuno", value: "breakfast" },
  { label: "Brunch", value: "brunch" },
  { label: "Comida o cena", value: "lunch/dinner" },
  { label: "Tentempié", value: "snack" },
  { label: "Merienda", value: "teatime" }
];

export const CUISINE_OPTIONS = [
  { label: "Americana", value: "american" },
  { label: "Asiática", value: "asian" },
  { label: "Británica", value: "british" },
  { label: "Caribeña", value: "caribbean" },
  { label: "Centroeuropea", value: "central europe" },
  { label: "China", value: "chinese" },
  { label: "Europa del este", value: "eastern europe" },
  { label: "Francesa", value: "french" },
  { label: "Griega", value: "greek" },
  { label: "India", value: "indian" },
  { label: "Italiana", value: "italian" },
  { label: "Japonesa", value: "japanese" },
  { label: "Coreana", value: "korean" },
  { label: "Kosher", value: "kosher" },
  { label: "Mediterránea", value: "mediterranean" },
  { label: "Mexicana", value: "mexican" },
  { label: "Oriente medio", value: "middle eastern" },
  { label: "Nórdica", value: "nordic" },
  { label: "Sudamericana", value: "south american" },
  { label: "Sudeste asiático", value: "south east asian" },
  { label: "Mundial", value: "world" }
];

export const TRANSLATIONS = {
  cuisineType: {
    american: "Americana",
    asian: "Asiática",
    british: "Británica",
    caribbean: "Caribeña",
    "central europe": "Centroeuropea",
    chinese: "China",
    "eastern europe": "Europa del este",
    french: "Francesa",
    greek: "Griega",
    indian: "India",
    italian: "Italiana",
    japanese: "Japonesa",
    korean: "Coreana",
    kosher: "Kosher",
    mediterranean: "Mediterránea",
    mexican: "Mexicana",
    "middle eastern": "Oriente medio",
    nordic: "Nórdica",
    "south american": "Sudamericana",
    "south east asian": "Sudeste asiático",
    world: "Mundial"
  },
  mealType: {
    breakfast: "Desayuno",
    brunch: "Brunch",
    "lunch/dinner": "Comida o cena",
    snack: "Tentempié",
    teatime: "Merienda"
  },
  dishType: {
    "alcohol cocktail": "Cócteles",
    "biscuits and cookies": "Galletas",
    bread: "Pan",
    cereals: "Cereales",
    "condiments and sauces": "Salsas",
    desserts: "Postres",
    drinks: "Bebidas",
    egg: "Huevo",
    "ice cream and custard": "Helados y cremas",
    "main course": "Plato principal",
    pancake: "Tortitas",
    pasta: "Pasta",
    pastry: "Bollería",
    "pies and tarts": "Tartas",
    pizza: "Pizza",
    preps: "Preparaciones",
    preserve: "Conservas",
    salad: "Ensaladas",
    sandwiches: "Sándwiches",
    seafood: "Marisco",
    "side dish": "Guarnición",
    soup: "Sopas",
    "special occasions": "Celebraciones",
    starter: "Entrantes",
    sweets: "Dulces"
  }
};
